# https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/building_applications/quotas
# oc apply -f ClusterResourceQuota.yml
apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  name: podman201
spec:
  quota:
    hard:
      secrets: '150'
      persistentvolumeclaims: '0'
      replicationcontrollers: '0'
      requests.cpu: 20
      requests.memory: 25Gi
      pods: '175'
      limits.cpu: 20
      limits.memory: 25Gi
      configmaps: '50'
      services: '75'
      pods: "250"
      secrets: "500"
  selector:
    labels:
      matchLabels:
        workshop: podman201
