# Deploy using the command "oc apply -f https://raw.githubusercontent.com/pablo-preciado/wod-podman201/master/Resources/patient-portal.yaml"
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: patient-portal-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
  namespace: patient-portal-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/patient-portal
        image: quay.io/skupper/patient-portal-database
        name: patient-portal-database
        ports:
        - containerPort: 5432
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-processor
  name: payment-processor
  namespace: patient-portal-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-processor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
      - image: quay.io/skupper/patient-portal-payment-processor
        name: patient-portal-payment-processor
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels: 
    app: frontend
  name: frontend
  namespace: patient-portal-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: frontend
    spec:   
      containers:
      - env:  
        - name: DATABASE_SERVICE_HOST
          value: database
        - name: DATABASE_SERVICE_PORT
          value: "5432"
        - name: PAYMENT_PROCESSOR_SERVICE_HOST
          value: payment-processor
        - name: PAYMENT_PROCESSOR_SERVICE_PORT
          value: "8080"
        image: quay.io/skupper/patient-portal-frontend
        name: patient-portal-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: patient-portal-application
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: patient-portal-application
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-processor
  name: payment-processor
  namespace: patient-portal-application
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: payment-processor
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: patient-portal-application
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: frontend
